name: Energy Price
version: "0.2.3"
slug: energy-price
description: Dynamic electricity price integration
url: https://github.com/SAMBA-Smart-Asset-Management/samba-energy-price
arch:
  - amd64
startup: application
boot: auto
init: false
hassio_api: true

options: {}
schema: {}

map:
  - config:rw
image: ghcr.io/samba-smart-asset-management/energy-price
